### ISSUE TITLE
[meta] Project Phoebus: The Second Generation Add-ons Site

### ISSUE THREAD

**Issue by mattatobin** [Pale-Moon-Addons-Team/phoebus#1]
This is a meta bug to track the progress of Project Phoebus.

- [x] Main Application with Services
- [ ] Submit Add-on Form
- [ ] No FTP
- [ ] SQL
- [ ] Self Service
- [ ] Web Administration
- [ ] Advanced Self Service
